name: Trigger auto deployment for jefmarti-aca-gha

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/jefmarti-aca-gha-AutoDeployTrigger-0a925bac-652d-4876-a51d-210466534b75.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #Not used when client secret auth is configured
      contents: read #Required when GH token is used to authenticate with private repo
    env:
      ACA_RESOURCE_GROUP: ${{ vars.ACA_RESOURCE_GROUP }}
      ACA_APP_NAME: ${{ vars.ACA_APP_NAME }}
      ACA_ENV_NAME: ${{ vars.ACA_ENV_NAME }}
      ACA_ACR_NAME: ${{ vars.ACA_ACR_NAME }}
      ACA_LOCATION: ${{ vars.ACA_LOCATION }}
      ACA_TARGET_PORT: ${{ vars.ACA_TARGET_PORT || '8000' }}

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.JEFMARTIACAGHA_AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.JEFMARTIACAGHA_AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.JEFMARTIACAGHA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.JEFMARTIACAGHA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: ${{ env.ACA_ACR_NAME }}
          containerAppName: ${{ env.ACA_APP_NAME }}
          resourceGroup: ${{ env.ACA_RESOURCE_GROUP }}
          containerAppEnvironment: ${{ env.ACA_ENV_NAME }}
          location: ${{ env.ACA_LOCATION }}
          ingress: external
          targetPort: ${{ env.ACA_TARGET_PORT }}
          runtimeStack: "python:3.11"
          environmentVariables: |
            PORT=${{ env.ACA_TARGET_PORT }}


